jwt:
  expiration: 2592000
  expiration-refresh: 5184000
  secretKey: ZGFpaG9jY29uZ25naGllcHRoYW5ocGhvaG9jaGltaW5o
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP}
spring:
  application:
    name: identity-service
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  security:
    user:
      name: root
      password: 12345678
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaspring0406@gmail.com
    password: jtnv nsrf hkos jwas
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
api:
  prefix: /api/v1
url:
  frontend: ${FRONTEND_URL}
httpClient:
  IdentityService:
    url: http://identity-service/api/v1
server:
  port: 8081

