jwt:
  expiration: 2592000
  expiration-refresh: 5184000
  secretKey: ZGFpaG9jY29uZ25naGllcHRoYW5ocGhvaG9jaGltaW5o
eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_URI}
  instance:
    ip-address: ${HOST_IP}
    prefer-ip-address: true
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: exercise-service
  data:
    mongodb:
      uri: mongodb+srv://minh:123456789a@mycluser.04jrsqv.mongodb.net/?retryWrites=true&w=majority&appName=myCluser
      database: exercise-service
amazon-properties:
  region:
  access-key:
  secret-key:
  bucket-name:
server:
  port: 8085
  servlet:
        context-path: /api/v1/exercise

api:
  url: http://localhost:8081/api/v1


